<!-- (A) HEADER -->
<header class="cb-head">
  <!-- (A1) TITLE -->
  <h1 class="cb-head-title">My Pictures</h1>

  <!-- (A2) BUTTONS -->
  <div class="cb-head-btn">
    <a class="card--link" href="#home">Open Camera</a>
    <p></p>
  </div>
</header>

<!-- (B) GALLERY PICTURES -->
<div id="gallery-pics"></div>
<template id="gallery-template"
  ><div class="pic">
    <img class="img" />
    <div class="btn">
      <button class="mi del">Delete Photo</button>
      <button class="mi get">Download Photo</button>
    </div>
  </div></template
>
